movieproject/movieapps/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='movieapps'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from movieproject import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapps.urls')),
]

if settings . DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

movieproject/movieapps/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallary')


    def __str__(self):
        return self.name

movieproject/movieapps/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapps/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from.models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    moviez=Movie.objects.get(id=movie_id)
    return render(request,'details.html',{'movie':moviez})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc= request.POST.get('desc', )
        year= request.POST.get('year', )
        img= request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter the name">
  <input type="text" name="desc" placeholder="enter the discribiction">
  <input type="text" name="year" placeholder="enter the year">
  <input type="file" name="img">
  <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">new movies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar navbar-expand-lg bg-body-tertiary"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Pricing</a>
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </div>
    </div>
  </div>
</nav>
<h1>movies</h1>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  are you want to delete it
  <input type="submit">

</form>

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="100" height="300">
        </div>


<div class="col-md-6">
    {{movie.name}}
    {{movie.desc}}
    {{movie.year}}
    <a class ="btn btn-warning" href="{% url 'movieapps:update' movie.id %}">update</a><br>
    <a class ="btn btn-danger" href="{% url 'movieapps:delete' movie.id %}">delete</a><br>
</div>







    </div>

</div>


{% endblock %}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}



<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="Card-img-top" alt="" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapps:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>

</div>







{% endblock %}